# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5cc8de566d65596b46f1777fc8a947b9dfd140e62122cff5ed65f11ecdd7b3a2cc41e82c907bb51d28988779bf0c060500a708fe60ce48ea4de81fb7851b4bc

test:
  secret_key_base: 02f3cdd20b55af045eda3dea9a97c531e315bd1757a499df10184932e0ccaf239fd0dfb1433315651023d98c459b213cc4b707a70dd38eaed9481fd25d70e465

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
